### ISSUE TITLE
Loopback is not finding the installed loopback-connector-couchbase module

### ISSUE THREAD

**Issue by djonk** [guardly/loopback-connector-couchbase#12]
On Windows I have the following issue: loopback doesn't seem to find the installed connector module. The connector installed without any issues or errors, but doesn't seem to work. Running the application returns: 

WARNING: LoopBack connector "couchbase" is not installed as any of the following modules:
 ./connectors/couchbase
loopback-connector-couchbase
couchbase

To fix, run:
    npm install couchbase

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error:
WARNING: LoopBack connector "couchbase" is not installed as any of the following modules:

 ./connectors/couchbase
loopback-connector-couchbase
couchbase

**Comment by djonk** [comment]
After some more debugging the issue seemed to be in the couchbase module. 
[Error: Failed to locate couchnode native binding (maybe check builderror.log!)]

On a Windows machine I took the following steps to resolve the issue: 

1) Install node-gyp:  npm install -g node-gyp
2) Install Python > 2.5 < 3.0 using the Windows installer
3) You need a C/C++ compiler. The easiest way on Windows, is to install Visual Studio. Express 2012 for Windows Desktop works well.
4) Install node.js couchbase module - this will automatically compile the source: npm install couchbase

**Comment by matteospampani** [comment]
This issue isn't related to loopback-connector-couchbase, right? The error was inside the couchbase module...

**Comment by djonk** [comment]
That's right, although the loopback-connector-couchbase is not particularly helpful in diagnosing the issue :)

**Comment by matteospampani** [comment]
Yes! :) But I think the problem is outside this module. I had a similar problems installing loopback-connector-couchbase on Ubuntu 12.04 with Node 0.12: *couchbase* installation fails on *node-gyp [...] rebuild* without notifying errors, then inside *builderror.log* was reported the error.
