### ISSUE TITLE
Ids are just UUID

### ISSUE THREAD

**Issue by janober** [guardly/loopback-connector-couchbase#3]
Hello,

first wanted to thank you for creating and sharing that connector! Will be a big help for me! Wanted to give feedback like requested in the description about the IDs.

In my eyes it is incredible important to be able to set custom keys. Seeing that Couchbase comes from a key-value-store and is also pretty much still one, being able to access a document directly with for example a compound key is essential to model the data to get the incredible speed people expect from Couchbase and why they choose it in the first place (like described in that Data Modeling Video https://www.youtube.com/watch?v=gfFuMRh2Ffc). Without it, a big advantage is missing.

The video gives multiple use cases like for example setting the key for users to: "user::test@example.com" or for products to: "p::12345". So documents can directly be pinpointed and accessed without any searching at all and you get incredible performance.

For me for example without that feature there is almost no reason to use Couchbase.

Hope that helps and that is what you wanted.

Was wondering if you already looked into that or started already and know how much work it would be to implement?

Thanks!

**Comment by janober** [comment]
Ehm, I just looked through the source code to see what changes would be needed. But for me it looks like it should already work. That a custom id can be given and an UUID only gets auto-generated when no "id" property is set on the data.

So did I understand the comment in the description wrong? If so please tell me then this can simply be deleted or closed. Thanks!

**Comment by nolandubeau** [comment]
Hi,  you are correct.  You can pass in an id value and that will be set as an id property in the document and as the document key.  I have updated the description in the Readme. Please let us know if you encounter any issues with this approach.

**Comment by janober** [comment]
Great, thanks a lot! Thats perfect then and exactly what I was looking for.

Will give it a try the next days.
